name: Build libcFMS test with CMake

on: [push, pull_request]

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  cmake_install:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.25.x'
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install netcdf-bin libnetcdf-dev libnetcdff-dev libyaml-dev -qq mpich libmpich-dev
    - name: test
      run: |
        export FC="mpifort"
        export CC="mpicc"
        export CFLAGS="-g -O0"
        export FCFLAGS="-g -O0 -W -fbacktrace -fbounds-check -fbacktrace -ffpe-trap=invalid,zero,overflow"
        cmake -B build -DCFMS_TESTS=ON
        cmake --build build